-- Disable Row Level Security (RLS) for all tables

ALTER TABLE cities DISABLE ROW LEVEL SECURITY;
ALTER TABLE hubs DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE cars DISABLE ROW LEVEL SECURITY;
ALTER TABLE drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE b2c_customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE fare_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE b2b_clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE b2b_entities DISABLE ROW LEVEL SECURITY;
ALTER TABLE b2b_employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE airports DISABLE ROW LEVEL SECURITY;
ALTER TABLE airport_terminals DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE cancellation_policies DISABLE ROW LEVEL SECURITY;
ALTER TABLE promo_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE city_polygons DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE gst_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE communication_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_event_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE duty_slips DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
